import org.jetbrains.intellij.platform.gradle.TestFrameworkType

plugins {
    id 'org.jetbrains.intellij.platform' version "2.2.1"
    id 'java'
    id 'io.freefair.lombok' version '6.6'
}

repositories {
    mavenCentral()
    mavenLocal()
    maven { // Gets snapshots of antlr if needed
        url "https://oss.sonatype.org/content/repositories/snapshots/"
    }

    intellijPlatform {
        defaultRepositories()
    }
}

apply plugin: 'java'
apply plugin: 'org.jetbrains.intellij.platform'
apply plugin: 'antlr'

tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.WARN
}

compileJava {
    sourceCompatibility = '17'
    targetCompatibility = '17'
}


def getVersionCode() {
    try {
        def outs = new ByteArrayOutputStream()
        exec {
            commandLine 'git', 'describe'
            standardOutput = outs
        }

        println("Plugin version --- v${outs.toString().trim()} ---")

        return outs.toString().trim()
    }
    catch (ignored) {
        return "?"
    }
}

//println(getVersion())


intellijPlatform {
    buildSearchableOptions = false
    instrumentCode = false

    pluginConfiguration {
        id = projectID
        name = projectName
        version = getVersionCode()
        description = ''
        changeNotes =
                """
      A descriptive release note...
      """.stripIndent()

//        productDescriptor {
//            code = 'MY_CODE'
//            releaseDate = '20250217'
//            releaseVersion = '20251'
//            optional = false
//            eap = false
//        }

        ideaVersion {
            sinceBuild = ideaVersionSince
            untilBuild = ideaVersionUntil
        }

        vendor {
            name = 'Lindenberg Research'
            email = 'lindenberg.research@gmail.com'
        }
    }
}


dependencies {
    intellijPlatform {
        intellijIdeaCommunity ideaVersion
        bundledPlugin 'com.intellij.java'
        testFramework TestFrameworkType.Platform.INSTANCE
    }

    antlr("org.antlr:antlr4:4.13.2") { // use ANTLR version 4
        exclude group: 'com.ibm.icu', module: 'icu4j'
    }

    implementation 'javax.inject:javax.inject:1'
    implementation "org.antlr:antlr4-intellij-adaptor:0.1"
    implementation group: 'org.jfree', name: 'org.jfree.svg', version: '5.0.6'
    implementation "org.projectlombok:lombok:1.18.24"

    testImplementation group: 'junit', name: 'junit', version: '4.13.2'
    testImplementation group: 'org.mockito', name: 'mockito-core', version: '5.14.1'
}

generateGrammarSource {
    include("**/ANTLRv4*.g4")

    arguments += [
            "-package", "org.antlr.intellij.plugin.parser",
            "-lib", "src/main/antlr/org/antlr/intellij/plugin/parser",
            "-Xexact-output-dir"
    ]
}

test {
    testLogging {
        events "failed"
        exceptionFormat "full"
    }
}

runIde {
    jvmArgs '-Xmx8G'
}
